{{- if .Values.ingress.host -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "onedev.fullname" . }}
  {{- if .Values.letsencrypt.email }}
  annotations:
    cert-manager.io/issuer: "{{ include "onedev.fullname" . }}"
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.class }}
  {{- if .Values.ingress.tls }}
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ include "onedev.fullname" . }}-tls
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ include "onedev.fullname" . }}-http
              port: 
                number: 80
{{- end }}
