namespace: onedev
commonLabels:
  app: onedev
secretGenerator:
- name: mysql
  literals:
  - password=changeit
resources:
- namespaces.yaml
- service-accounts.yaml
- roles.yaml
- role-bindings.yaml
- services.yaml
- deployments.yaml
- persistent-volume-claims.yaml
