apiVersion: v1
kind: Service
metadata:
  name: onedev
  labels:
    tier: server
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 6610
    protocol: TCP
  selector:
    tier: server
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    tier: database
spec:
  ports:
    - port: 3306
  selector:
    tier: database
